-- Database: SolBooking

-- DROP DATABASE "SolBooking";

CREATE DATABASE "SolBooking"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
	
	
	
-- Table: public.hotels

-- DROP TABLE public.hotels;

CREATE TABLE public.hotels
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    phone character varying COLLATE pg_catalog."default",
    mail character varying COLLATE pg_catalog."default",
    CONSTRAINT "Hotels_pkey" PRIMARY KEY (id),
    CONSTRAINT hotels_name_unique UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE public.hotels
    OWNER to postgres;
	
	
	
	
	
	
-- Table: public.users

-- DROP TABLE public.users;

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username character varying COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default",
    refresh_token character varying COLLATE pg_catalog."default",
    CONSTRAINT "Users_pkey" PRIMARY KEY (id),
    CONSTRAINT users_username_unique UNIQUE (username)
)

TABLESPACE pg_default;

ALTER TABLE public.users
    OWNER to postgres;
	
	
	
	
	
-- Table: public.users_hotels

-- DROP TABLE public.users_hotels;

CREATE TABLE public.users_hotels
(
    id_user integer NOT NULL,
    id_hotel integer NOT NULL,
    CONSTRAINT "Users_Hotels_pkey" PRIMARY KEY (id_user, id_hotel),
    CONSTRAINT "idHotel_hotel_id" FOREIGN KEY (id_hotel)
        REFERENCES public.hotels (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID,
    CONSTRAINT "idUser_user_id" FOREIGN KEY (id_user)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public.users_hotels
    OWNER to postgres;